server:
  # 服务端口号
  port: 80
spring:
  application:
    # 服务名称 - 服务之间使用名称进行通讯
    name: edu-authority-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/edu_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ZhengChao@666
  redis:
    host: 192.168.40.128
    port: 6379
eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://localhost:7001/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ali:
  sms:
    signName: 拉勾教育通知
    templateCode: SMS_xxx
    assessKeyId: LTAI5
    assessKeySecret: xoDrk5
